// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package api.protobuf;

/**
 * Protobuf type {@code api.protobuf.ActivityConfig}
 */
public  final class ActivityConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.protobuf.ActivityConfig)
    ActivityConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActivityConfig.newBuilder() to construct.
  private ActivityConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActivityConfig() {
    activities_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActivityConfig();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ActivityConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            detectionIntervalMillis_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              activities_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            activities_.add(rawValue);
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                activities_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              activities_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        activities_ = java.util.Collections.unmodifiableList(activities_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return api.protobuf.Api.internal_static_api_protobuf_ActivityConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return api.protobuf.Api.internal_static_api_protobuf_ActivityConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            api.protobuf.ActivityConfig.class, api.protobuf.ActivityConfig.Builder.class);
  }

  public static final int DETECTIONINTERVALMILLIS_FIELD_NUMBER = 1;
  private long detectionIntervalMillis_;
  /**
   * <pre>
   *Через какое время получить данные об активности
   * </pre>
   *
   * <code>int64 detectionIntervalMillis = 1;</code>
   * @return The detectionIntervalMillis.
   */
  public long getDetectionIntervalMillis() {
    return detectionIntervalMillis_;
  }

  public static final int ACTIVITIES_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Integer> activities_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, api.protobuf.Activity> activities_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, api.protobuf.Activity>() {
            public api.protobuf.Activity convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              api.protobuf.Activity result = api.protobuf.Activity.valueOf(from);
              return result == null ? api.protobuf.Activity.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   *Какие типы активностей отслеживать
   * </pre>
   *
   * <code>repeated .api.protobuf.Activity activities = 2;</code>
   * @return A list containing the activities.
   */
  public java.util.List<api.protobuf.Activity> getActivitiesList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, api.protobuf.Activity>(activities_, activities_converter_);
  }
  /**
   * <pre>
   *Какие типы активностей отслеживать
   * </pre>
   *
   * <code>repeated .api.protobuf.Activity activities = 2;</code>
   * @param value The activities to add.
   */
  public int getActivitiesCount() {
    return activities_.size();
  }
  /**
   * <pre>
   *Какие типы активностей отслеживать
   * </pre>
   *
   * <code>repeated .api.protobuf.Activity activities = 2;</code>
   * @param index The index of the element to return.
   * @return The activities at the given index.
   */
  public api.protobuf.Activity getActivities(int index) {
    return activities_converter_.convert(activities_.get(index));
  }
  /**
   * <pre>
   *Какие типы активностей отслеживать
   * </pre>
   *
   * <code>repeated .api.protobuf.Activity activities = 2;</code>
   * @return A list containing the enum numeric values on the wire for activities.
   */
  public java.util.List<java.lang.Integer>
  getActivitiesValueList() {
    return activities_;
  }
  /**
   * <pre>
   *Какие типы активностей отслеживать
   * </pre>
   *
   * <code>repeated .api.protobuf.Activity activities = 2;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of activities at the given index.
   */
  public int getActivitiesValue(int index) {
    return activities_.get(index);
  }
  private int activitiesMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (detectionIntervalMillis_ != 0L) {
      output.writeInt64(1, detectionIntervalMillis_);
    }
    if (getActivitiesList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(activitiesMemoizedSerializedSize);
    }
    for (int i = 0; i < activities_.size(); i++) {
      output.writeEnumNoTag(activities_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (detectionIntervalMillis_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, detectionIntervalMillis_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < activities_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(activities_.get(i));
      }
      size += dataSize;
      if (!getActivitiesList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }activitiesMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof api.protobuf.ActivityConfig)) {
      return super.equals(obj);
    }
    api.protobuf.ActivityConfig other = (api.protobuf.ActivityConfig) obj;

    if (getDetectionIntervalMillis()
        != other.getDetectionIntervalMillis()) return false;
    if (!activities_.equals(other.activities_)) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DETECTIONINTERVALMILLIS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDetectionIntervalMillis());
    if (getActivitiesCount() > 0) {
      hash = (37 * hash) + ACTIVITIES_FIELD_NUMBER;
      hash = (53 * hash) + activities_.hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static api.protobuf.ActivityConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.protobuf.ActivityConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.protobuf.ActivityConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.protobuf.ActivityConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.protobuf.ActivityConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.protobuf.ActivityConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.protobuf.ActivityConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.protobuf.ActivityConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.protobuf.ActivityConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static api.protobuf.ActivityConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.protobuf.ActivityConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.protobuf.ActivityConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(api.protobuf.ActivityConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.protobuf.ActivityConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.protobuf.ActivityConfig)
      api.protobuf.ActivityConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return api.protobuf.Api.internal_static_api_protobuf_ActivityConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return api.protobuf.Api.internal_static_api_protobuf_ActivityConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              api.protobuf.ActivityConfig.class, api.protobuf.ActivityConfig.Builder.class);
    }

    // Construct using api.protobuf.ActivityConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      detectionIntervalMillis_ = 0L;

      activities_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return api.protobuf.Api.internal_static_api_protobuf_ActivityConfig_descriptor;
    }

    @java.lang.Override
    public api.protobuf.ActivityConfig getDefaultInstanceForType() {
      return api.protobuf.ActivityConfig.getDefaultInstance();
    }

    @java.lang.Override
    public api.protobuf.ActivityConfig build() {
      api.protobuf.ActivityConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public api.protobuf.ActivityConfig buildPartial() {
      api.protobuf.ActivityConfig result = new api.protobuf.ActivityConfig(this);
      int from_bitField0_ = bitField0_;
      result.detectionIntervalMillis_ = detectionIntervalMillis_;
      if (((bitField0_ & 0x00000001) != 0)) {
        activities_ = java.util.Collections.unmodifiableList(activities_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.activities_ = activities_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof api.protobuf.ActivityConfig) {
        return mergeFrom((api.protobuf.ActivityConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(api.protobuf.ActivityConfig other) {
      if (other == api.protobuf.ActivityConfig.getDefaultInstance()) return this;
      if (other.getDetectionIntervalMillis() != 0L) {
        setDetectionIntervalMillis(other.getDetectionIntervalMillis());
      }
      if (!other.activities_.isEmpty()) {
        if (activities_.isEmpty()) {
          activities_ = other.activities_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureActivitiesIsMutable();
          activities_.addAll(other.activities_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      api.protobuf.ActivityConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (api.protobuf.ActivityConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long detectionIntervalMillis_ ;
    /**
     * <pre>
     *Через какое время получить данные об активности
     * </pre>
     *
     * <code>int64 detectionIntervalMillis = 1;</code>
     * @return The detectionIntervalMillis.
     */
    public long getDetectionIntervalMillis() {
      return detectionIntervalMillis_;
    }
    /**
     * <pre>
     *Через какое время получить данные об активности
     * </pre>
     *
     * <code>int64 detectionIntervalMillis = 1;</code>
     * @param value The detectionIntervalMillis to set.
     * @return This builder for chaining.
     */
    public Builder setDetectionIntervalMillis(long value) {
      
      detectionIntervalMillis_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Через какое время получить данные об активности
     * </pre>
     *
     * <code>int64 detectionIntervalMillis = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDetectionIntervalMillis() {
      
      detectionIntervalMillis_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> activities_ =
      java.util.Collections.emptyList();
    private void ensureActivitiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        activities_ = new java.util.ArrayList<java.lang.Integer>(activities_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @return A list containing the activities.
     */
    public java.util.List<api.protobuf.Activity> getActivitiesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, api.protobuf.Activity>(activities_, activities_converter_);
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @return The count of activities.
     */
    public int getActivitiesCount() {
      return activities_.size();
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @param index The index of the element to return.
     * @return The activities at the given index.
     */
    public api.protobuf.Activity getActivities(int index) {
      return activities_converter_.convert(activities_.get(index));
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @param index The index to set the value at.
     * @param value The activities to set.
     * @return This builder for chaining.
     */
    public Builder setActivities(
        int index, api.protobuf.Activity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureActivitiesIsMutable();
      activities_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @param value The activities to add.
     * @return This builder for chaining.
     */
    public Builder addActivities(api.protobuf.Activity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureActivitiesIsMutable();
      activities_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @param values The activities to add.
     * @return This builder for chaining.
     */
    public Builder addAllActivities(
        java.lang.Iterable<? extends api.protobuf.Activity> values) {
      ensureActivitiesIsMutable();
      for (api.protobuf.Activity value : values) {
        activities_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearActivities() {
      activities_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @return A list containing the enum numeric values on the wire for activities.
     */
    public java.util.List<java.lang.Integer>
    getActivitiesValueList() {
      return java.util.Collections.unmodifiableList(activities_);
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of activities at the given index.
     */
    public int getActivitiesValue(int index) {
      return activities_.get(index);
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of activities at the given index.
     * @return This builder for chaining.
     */
    public Builder setActivitiesValue(
        int index, int value) {
      ensureActivitiesIsMutable();
      activities_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @param value The enum numeric value on the wire for activities to add.
     * @return This builder for chaining.
     */
    public Builder addActivitiesValue(int value) {
      ensureActivitiesIsMutable();
      activities_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Какие типы активностей отслеживать
     * </pre>
     *
     * <code>repeated .api.protobuf.Activity activities = 2;</code>
     * @param values The enum numeric values on the wire for activities to add.
     * @return This builder for chaining.
     */
    public Builder addAllActivitiesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureActivitiesIsMutable();
      for (int value : values) {
        activities_.add(value);
      }
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.protobuf.ActivityConfig)
  }

  // @@protoc_insertion_point(class_scope:api.protobuf.ActivityConfig)
  private static final api.protobuf.ActivityConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new api.protobuf.ActivityConfig();
  }

  public static api.protobuf.ActivityConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActivityConfig>
      PARSER = new com.google.protobuf.AbstractParser<ActivityConfig>() {
    @java.lang.Override
    public ActivityConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ActivityConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActivityConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActivityConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public api.protobuf.ActivityConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

