// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package api.protobuf;

/**
 * Protobuf enum {@code api.protobuf.Activity}
 */
public enum Activity
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>IN_VEHICLE = 0;</code>
   */
  IN_VEHICLE(0),
  /**
   * <code>ON_BICYCLE = 1;</code>
   */
  ON_BICYCLE(1),
  /**
   * <code>ON_FOOT = 2;</code>
   */
  ON_FOOT(2),
  /**
   * <code>STILL = 3;</code>
   */
  STILL(3),
  /**
   * <code>UNKNOWN = 4;</code>
   */
  UNKNOWN(4),
  /**
   * <code>TILTING = 5;</code>
   */
  TILTING(5),
  /**
   * <code>WALKING = 7;</code>
   */
  WALKING(7),
  /**
   * <code>RUNNING = 8;</code>
   */
  RUNNING(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>IN_VEHICLE = 0;</code>
   */
  public static final int IN_VEHICLE_VALUE = 0;
  /**
   * <code>ON_BICYCLE = 1;</code>
   */
  public static final int ON_BICYCLE_VALUE = 1;
  /**
   * <code>ON_FOOT = 2;</code>
   */
  public static final int ON_FOOT_VALUE = 2;
  /**
   * <code>STILL = 3;</code>
   */
  public static final int STILL_VALUE = 3;
  /**
   * <code>UNKNOWN = 4;</code>
   */
  public static final int UNKNOWN_VALUE = 4;
  /**
   * <code>TILTING = 5;</code>
   */
  public static final int TILTING_VALUE = 5;
  /**
   * <code>WALKING = 7;</code>
   */
  public static final int WALKING_VALUE = 7;
  /**
   * <code>RUNNING = 8;</code>
   */
  public static final int RUNNING_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Activity valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Activity forNumber(int value) {
    switch (value) {
      case 0: return IN_VEHICLE;
      case 1: return ON_BICYCLE;
      case 2: return ON_FOOT;
      case 3: return STILL;
      case 4: return UNKNOWN;
      case 5: return TILTING;
      case 7: return WALKING;
      case 8: return RUNNING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Activity>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Activity> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Activity>() {
          public Activity findValueByNumber(int number) {
            return Activity.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return api.protobuf.Api.getDescriptor().getEnumTypes().get(2);
  }

  private static final Activity[] VALUES = values();

  public static Activity valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Activity(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.protobuf.Activity)
}

